workflows:
  main:
    name: CI/CD Workflow

    environment:
      flutter: stable

    scripts:
      - name: Install Java 11
        script: |
          brew update
          brew install -y openjdk-11-jdk
          export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64

      - name: Install Google Cloud CLI
        script: |
          curl https://sdk.cloud.google.com | bash
          exec -l $SHELL
          gcloud init

      - name: Authenticate with Google Cloud
        script: |
          gcloud auth activate-service-account terraform-service-account@gcp-pocs-386219.iam.gserviceaccount.com --key-file=3750b13c75a4500e26b7837213d01fd409a5b6dd
          gcloud config set project gcp-pocs-386219

      - name: 'Flutter Pub Get'
        script: flutter pub get

      - name: 'Flutter Build AAR'
        script: flutter build aar

      - name: 'Set app/build.gradle versions'
        script: |
          perl -i -p0e 's/compileSdkVersion 31/compileSdkVersion 33/g' .android/app/build.gradle
          perl -i -p0e 's/minSdkVersion 16/minSdkVersion 19/g' .android/app/build.gradle
          perl -i -p0e 's/targetSdkVersion 31/targetSdkVersion 33/g' .android/app/build.gradle

      - name: 'Append build.gradle script'
        script: |
          cat .android/build.gradle

      - name: 'Append publish.gradle script'
        script: |
          apply plugin: 'maven-publish'

            publishing {
              publications {
                mavenJava(MavenPublication) {
                    from components.java
                 }
               }
                repositories {
                   maven {
                       name = "googleArtifactRegistry"
                       url = uri("https://console.cloud.google.com/artifacts/maven/gcp-pocs-386219/northamerica-northeast2/think-research-maven-repo")
                      credentials(HttpHeaderCredentials) {
                         name = "terraform-service-account@gcp-pocs-386219.iam.gserviceaccount.com"
                         value = "3750b13c75a4500e26b7837213d01fd409a5b6dd"
                      }
                   }
                }
            }


      # You can add more scripts or steps as needed
