workflows:
  main:
    name: CI/CD Workflow

    environment:
      flutter: stable

    scripts:
      - name: Run Flutter Analyzer
        script: flutter analyze

      - name: Run Unit Tests
        script: flutter test

      - name: 'Flutter Pub Get'
        script: flutter pub get

      - name: 'Flutter Build AAR'
        script: flutter build aar

      

      # You can add more scripts or steps as needed
