workflows:
  main:
    name: CI/CD Workflow

    environment:
      flutter: stable

    scripts:
      - name: 'Flutter Pub Get'
        script: flutter pub get

      - name: 'Flutter Build AAR'
        script: flutter build aar

      - name: 'Set app/build.gradle versions'
        script: |
          perl -i -p0e 's/compileSdkVersion 31/compileSdkVersion 33/g' .android/app/build.gradle
          perl -i -p0e 's/minSdkVersion 16/minSdkVersion 19/g' .android/app/build.gradle
          perl -i -p0e 's/targetSdkVersion 31/targetSdkVersion 33/g' .android/app/build.gradle

      

      # You can add more scripts or steps as needed
