workflows:
  main:
    name: Publish Workflow

    # Triggers for the workflow
    triggers:
      - event: pull_request
        branch: main
        action: closed

    # Concurrency settings
    concurrency:
      group: $CI_COMMIT_REF_NAME-$CI_PIPELINE_ID
      cancel-in-progress: true

        environment:
          flutter: stable

        scripts:
          - name: Checkout
            script: git clone $CI_REPOSITORY_URL .

          - name: Check a new tag
            script: |
              TAG_VERSION=$(grep version pubspec.yaml | awk -F ': ' '{print $2}')
              echo "version=$TAG_VERSION" >> $CI_OUTPUT
              echo $TAG_VERSION
              git tag $TAG_VERSION
              git push origin $TAG_VERSION

          - name: Install Java 11
            script: |
              brew update
              brew install -y openjdk-11-jdk
              export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64

          - name: Install Google Cloud CLI
            script: |
              curl https://sdk.cloud.google.com | bash
              exec -l $SHELL
              gcloud init

          - name: 'Flutter Pub Get'
            script: flutter pub get

          - name: 'Flutter Build AAR'
            script: flutter build aar

          - name: 'Set app/build.gradle versions'
            script: |
              perl -i -p0e 's/compileSdkVersion 31/compileSdkVersion 33/g' .android/app/build.gradle
              perl -i -p0e 's/minSdkVersion 16/minSdkVersion 19/g' .android/app/build.gradle
              perl -i -p0e 's/targetSdkVersion 31/targetSdkVersion 33/g' .android/app/build.gradle

          - name: 'Append build.gradle script'
            script: |
              cat .android/build.gradle

          - name: Publish to Google Cloud
            script: | 
                echo $GCLOUD_STORAGE_KEY > $CM_BUILD_DIR/gcloud_storage_key.json
                gcloud auth activate-service-account --key-file $CM_BUILD_DIR/gcloud_storage_key.json
                gsutil cp $CM_BUILD_DIR/app/build/outputs/**/*.apk gs://think-research-maven-repo-bucket

          - name: 'Append publish.gradle script'
            script: |
              cat publish.gradle


          - name: 'Flutter Build AAR'
            run: |
              flutter build aar --no-debug --no-profile --build-number $TAG_VERSION
            # You can add more scripts or steps as needed
