name: components
description: Set of components for Altro App
version: 0.1.0
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  intl: ^0.18.0
  resources:
    path: ../resources
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true

