name: Publish

on:
  pull_request:
    branches:
      - main
    types:
      - closed

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  release:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.version }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'main'

      - name: Check a new tag
        id: tag
        run: |
          export TAG_VERSION=$(grep version pubspec.yaml |  awk -F  ': ' '{print $2}')
          echo "version=$TAG_VERSION" >> $GITHUB_OUTPUT
          echo $TAG_VERSION
          git tag $TAG_VERSION
          git push origin $TAG_VERSION
          echo ${{ github.actor }}

      - name: Create a Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag.outputs.version }}

  aar:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: "Checkout Thinkresearch Chat SDK Flutter"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout current tag
        run: |
          git checkout ${{needs.release.outputs.tag}}

      - name: 'Setup Flutter'
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.13.3'

      - name: 'Set up Java 17'
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: 'Flutter Pub Get'
        run: |
          flutter pub get

      - name: 'Flutter Build AAR'
        run: |
          flutter build aar

      - name: 'Set app/build.gradle versions'
        run: |
          perl -i -p0e 's/compileSdkVersion 31/compileSdkVersion 33/g' .android/app/build.gradle
          perl -i -p0e 's/minSdkVersion 16/minSdkVersion 19/g' .android/app/build.gradle
          perl -i -p0e 's/targetSdkVersion 31/targetSdkVersion 33/g' .android/app/build.gradle

      - name: 'Append publish.gradle script'
        run: |
          cat publish.gradle >> .android/build.gradle

      - name: 'Flutter Build AAR'
        run: |
          flutter build aar --no-debug --no-profile --build-number ${{needs.release.outputs.tag}}
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  xcframeworks:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/')
    runs-on: macos-latest
    needs: release
    steps:
      - name: "Checkout TIKI SDK Flutter"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout current tag
        run: |
          git checkout ${{needs.release.outputs.tag}}

      - name: "Setup Flutter"
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.3'

      - name: "Setup XCode"
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: 'Flutter pub get'
        run: |
          flutter pub get

      - name: 'Change Deployment Target in Xcode Project'
        run: |
          cd .ios
          perl -i -pe 's/IPHONEOS_DEPLOYMENT_TARGET = 11.0;/IPHONEOS_DEPLOYMENT_TARGET = 13.0;/g' Runner.xcodeproj/project.pbxproj
    

      - name: 'Add embed script in Xcode Project Build phases'
        run: |
          cd .ios
          perl -i -p0e 's/shellScript = "\/bin\/sh \\"\$FLUTTER_ROOT\/packages\/flutter_tools\/bin\/xcode_backend\.sh\\" build";/shellScript = "\/bin\/sh \\"\$FLUTTER_ROOT\/packages\/flutter_tools\/bin\/xcode_backend\.sh\\" build\\n\/bin\/sh \\"\$FLUTTER_ROOT\/packages\/flutter_tools\/bin\/xcode_backend\.sh\\" embed\\n";/s' ./Runner.xcodeproj/project.pbxproj

      - name: "Build Frameworks"
        run: |
          flutter build ios-framework --output=Frameworks --no-profile

      - name: "Create pod"
        run: |
          pod trunk push chatbot_sdk_channel.podspec --allow-warnings   

      


